# Generated by Django 5.1.1 on 2024-12-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_women_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
